# Generated by Django 5.2 on 2025-04-21 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Postura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha_siembra', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('AD', 'Adquirida'), ('TR', 'En Transito'), ('AL', 'Almacenada'), ('SM', 'Sembrada')], default='AD', max_length=2)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forestal_app.especie')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
