# Generated by Django 5.2 on 2025-04-21 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postura',
            name='estado',
            field=models.CharField(choices=[('Adquirida', 'Adquirida'), ('En Transporte', 'En Transito'), ('Almacenada', 'Almacenada'), ('Sembrada', 'Sembrada')], default='Adquirida'),
        ),
        migrations.AlterField(
            model_name='postura',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
