# Generated by Django 5.2 on 2025-04-22 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_app', '0002_alter_postura_estado_alter_postura_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('postura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='forestal_app.postura')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
