# Generated by Django 5.2 on 2025-04-22 19:25

import forestal_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_app', '0004_historialestado_delete_estadohistorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={'verbose_name': 'Historial de Estado', 'verbose_name_plural': 'Historiales de Estado'},
        ),
        migrations.AlterModelOptions(
            name='postura',
            options={'verbose_name': 'Postura', 'verbose_name_plural': 'Posturas'},
        ),
        migrations.RenameField(
            model_name='postura',
            old_name='fecha_siembra',
            new_name='fecha_adquisicion',
        ),
        migrations.AlterField(
            model_name='postura',
            name='estado',
            field=models.CharField(choices=[('Adquirida', 'Adquirida'), ('En Transporte', 'En Transito'), ('Almacenada', 'Almacenada'), ('Sembrada', 'Sembrada')], default='Adquirida', max_length=50),
        ),
        migrations.AlterField(
            model_name='postura',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[forestal_app.models.validar_latitud]),
        ),
        migrations.AlterField(
            model_name='postura',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[forestal_app.models.validar_longitud]),
        ),
    ]
