# Generated by Django 5.2 on 2025-04-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_app', '0005_alter_especie_options_alter_historialestado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postura',
            name='fecha_siembra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
