# Generated by Django 5.2 on 2025-04-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_app', '0007_postura_qr_code_escaneopostura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postura',
            options={},
        ),
    ]
