# Generated by Django 5.2 on 2025-04-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_app', '0008_alter_postura_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postura',
            options={'verbose_name': 'Postura', 'verbose_name_plural': 'Posturas'},
        ),
    ]
