# Generated by Django 5.2 on 2025-04-24 03:25

import django.db.models.deletion
import forestal_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forestal_app', '0009_alter_postura_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escaneopostura',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Escaneo de Postura', 'verbose_name_plural': 'Escaneos de Postura'},
        ),
        migrations.AlterModelOptions(
            name='historialestado',
            options={'ordering': ['-fecha_cambio'], 'verbose_name': 'Historial de Estado', 'verbose_name_plural': 'Historiales de Estado'},
        ),
        migrations.AlterModelOptions(
            name='postura',
            options={'ordering': ['-fecha_adquisicion'], 'verbose_name': 'Postura', 'verbose_name_plural': 'Posturas'},
        ),
        migrations.AddField(
            model_name='historialestado',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[forestal_app.models.validar_latitud]),
        ),
        migrations.AddField(
            model_name='historialestado',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[forestal_app.models.validar_longitud]),
        ),
        migrations.AlterField(
            model_name='escaneopostura',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[forestal_app.models.validar_latitud]),
        ),
        migrations.AlterField(
            model_name='escaneopostura',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[forestal_app.models.validar_longitud]),
        ),
        migrations.AlterField(
            model_name='escaneopostura',
            name='postura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaneos', to='forestal_app.postura'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre_cientifico',
            field=models.CharField(max_length=150, verbose_name='Nombre científico'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre_comun',
            field=models.CharField(max_length=100, verbose_name='Nombre común'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='fecha_cambio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio'),
        ),
        migrations.AlterField(
            model_name='postura',
            name='estado',
            field=models.CharField(choices=[('Adquirida', 'Adquirida'), ('En Transporte', 'En Transporte'), ('Almacenada', 'Almacenada'), ('Sembrada', 'Sembrada')], default='Adquirida', max_length=20),
        ),
    ]
